### ISSUE TITLE
set_accuracy() refactoring

### ISSUE THREAD

**Issue by ggorman** [opesci/opesci-fd#41]
1. set_accuracy() needs to be replaced with set_order(). Make sure that the parameters really do mean order. --- Follow the "Principle of least astonishment"

2. Currently the code fails with an unhelpful message when set_accuracy (to be renamed set_order()). Set a sensible default instead (e.g. 2nd order) and perhaps add some checks to make sure that something sensible is being asked for.

**Comment by tj-sun** [comment]
sorted now.

**Comment by mlange05** [comment]
Is this fixed now that PR #47 has landed?

**Comment by ctjacobs** [comment]
Yes.
