### ISSUE TITLE
Configure pep8 for travis-ci

### ISSUE THREAD

**Issue by ggorman** [opesci/opesci-fd#53]
Configure pep8 for travis-ci so that commits adhere to style guidelines. This would automatically catch various style issues such as those in pull request #52.

**Comment by mlange05** [comment]
This is already set up. Travis is already red for PR #52 and presenting a long list of style violations, mostly due to indentation through tabs.

**Comment by ggorman** [comment]
My bad - I forgot it had been added and only say the error at the end of the travis log.

BTW - I thought you were banned from touching computers for another while ;-)
