### ISSUE TITLE
Error message during install could be improved

### ISSUE THREAD

**Issue by navjotk** [opesci/opesci-fd#55]
While installing using the provided install instructions on a system that doesn't have CMake installed, the last line of the instructions ``python setup.py build_clib --build-clib=`pwd` `` produces an error message that is not especially informative. 

Expected behaviour
--------------------------
A helpful error message that describes the exact problem and steps needed to continue the installation. In this case it would describe the fact that CMake was not found and is required.

Actual behaviour
---------------------
A cryptic error message:
```
    error: [Errno 2] No such file or directory
```
It is not obvious on reading this message that the installation procedure failed because it did not find CMake.

**Comment by ctjacobs** [comment]
Can you provide the full backtrace please?

**Comment by ctjacobs** [comment]
Never mind. See pull request #56.

**Comment by navjotk** [comment]
Pull request #56 did indeed fix this. Thanks.
