### ISSUE TITLE
In-memory AST for generated C source code

### ISSUE THREAD

**Issue by mlange05** [opesci/opesci-fd#57]
Rather than generating pure strings to insert into a template file we should generate a tree/AST of C-code objects that we can manipulate before dumping the code to file. [Cgen](https://github.com/inducer/cgen), a package for representing C constructs down to declarations, loop constructs and statements, seems really useful for this. Generating cgen objects would not only allow us to write our own platform-specific code manipulation routines but also bring us closer to similar tools like [LooPy](https://github.com/inducer/loopy) or [PyCuda](http://mathema.tician.de/software/pycuda/)/[PyOpenCL](http://mathema.tician.de/software/pyopencl/), which are all closely related to [cgen](https://github.com/inducer/cgen).

Converting to `cgen` will likely require some significant refactoring of how we generate code, but it should also make things more readable and maintainable, since we can separate the pure code generation from the optimisation stage. It will also improve the pretty-printing of our generated code.

**Comment by navjotk** [comment]
I would like to commit some code for review but I don't have permission to create a branch on this repository. Could I have the access please?

**Comment by ctjacobs** [comment]
@tmbgreaves or @ggorman can add you to the opesci-core team. In the mean time, perhaps create your own fork of this repository and create a pull request that way?

**Comment by tmbgreaves** [comment]
Invite sent.

**Comment by ctjacobs** [comment]
Thanks Tim.

**Comment by navjotk** [comment]
Thanks Tim and Christian.

**Comment by mlange05** [comment]
Addressed in PR #60. Excellent work, thanks @navjotk
