### ISSUE TITLE
Add python interface via swig

### ISSUE THREAD

**Issue by ggorman** [opesci/opesci-fd#7]
Clearly the API will be in flux for a while. However, add the necessary infrastructure and a simple test example.

**Comment by mlange05** [comment]
Rather than relying on swig, I think we should provide our own Python interfaces for executing and analysing the auto-generated code. PR #30 contains the basic infrastructure for this, provided through the `Grid` class, as well as running the basic eigenwave3d test through the Python interface.

**Comment by ctjacobs** [comment]
Given that #30 has landed, can this be closed now?

**Comment by mlange05** [comment]
Yes, I think so. Closing
